name: Gold Price

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  gold-price:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -o gold-price .
      - name: Run
        env:
          SUPERSECRET_PRIVATE_KEY: ${{ secrets.SUPERSECRET_PRIVATE_KEY }}
        run: ./gold-price
